controller:
  replicaCount: 1

lvmd:
  managed: false

podSecurityPolicy:
  create: false

cert-manager:
  enabled: true

storageClasses:
  - name: topolvm-provisioner-new
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
  - name: topolvm-provisioner-thin-new
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "ssd-thin"

scheduler:
  options:
    listen:
      port: 9252

priorityClass:
  enabled: false
