on:
  workflow_call:
    inputs:
      test_scheduler_extender_type:
        type: string
      test_legacy:
        type: string

jobs:
  e2e-k8s:
    name: "e2e-k8s"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_versions: ["1.29.2", "1.28.7", "1.27.11"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
      TEST_SCHEDULER_EXTENDER_TYPE: ${{ inputs.test_scheduler_extender_type }}
      TEST_LEGACY: ${{ inputs.test_legacy }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: actions/cache/restore@v4
        with:
          path: |
            bin
            test/e2e/bin
            test/e2e/topolvm.img
          key: e2e-cache-${{ github.sha }}
      - run: touch test/e2e/topolvm.img # update timestamp not to rebuild image
      - run: make -C test/e2e start-lvmd
      - run: make -C test/e2e test
